PKG_NAME="re2"
PKG_VERSION="2017-05-01"
PKG_GIT_URL="https://github.com/google/re2"
PKG_DEPENDS_HOST=""
PKG_SECTION="devel"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"

PKG_CMAKE_OPTS_TARGET="-DBUILD_SHARED_LIBS=0 -DBUILD_TESTING=0"

PKG_CMAKE_OPTS_HOST="-DBUILD_SHARED_LIBS=0 -DBUILD_TESTING=0"