PKG_NAME="irqbalance"
PKG_VERSION="1.5.0"
PKG_SHA256="3318eddc03782cfdad22b20eff18eaf378c498c5de286e8cbaa5521ddf4f810b"
PKG_SITE="https://github.com/Irqbalance/irqbalance"
PKG_URL="https://github.com/Irqbalance/irqbalance/archive/v${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain glib systemd ncurses"
PKG_SHORTDESC="irqbalance: a daemon to help balance the cpu load generated by interrupts across all of a systems cpus"
PKG_TOOLCHAIN="autotools"

PKG_CONFIGURE_OPTS_TARGET="--with-systemd --without-libcap-ng"

post_makeinstall_target() {
  mkdir -p $INSTALL/etc
    cp $PKG_BUILD/misc/irqbalance.env $INSTALL/etc/irqbalance

  mkdir -p $INSTALL/usr/lib/systemd/system
    cp $PKG_BUILD/misc/irqbalance.service $INSTALL/usr/lib/systemd/system
}

post_install() {
  enable_service irqbalance.service
}
