#!/usr/bin/perl
# Carlos E. Gorges <carlos@techlinux.com.br>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
# Generate isapnp_mod_list.ids, isapnp_mod_type.ids and isapnp_mod_module.ids
# from the isapnpmod-list.lst file.

open S,	 "<isapnpmod-list.lst" || die();
while (<S>) {
	if(! ($_=~ /^[\ \n]$/ ) && ! ( $_ =~ /^#/ ) ) {
		my @l=split /\t/,$_; chomp($l[2]);
		die("Incomplete line: $_") if ( ! length($l[1]) || ! length($l[2]));

		@ids=(@ids,$l[0]);
		@fulltypes=(@fulltypes,$l[1]);
		@fullmods=(@fullmods,$l[2]);
		$i++;
	}
}
close(S);

open F1, ">../isapnp_mod_list.ids"	|| die();
open F2, ">../isapnp_mod_type.ids" || die();
open F3, ">../isapnp_mod_module.ids" || die();

my %types = ( "unknown" => 0 ) ;
my @typeslist = ( "unknown" );
$count=1;
foreach $a (@fulltypes) {
	$found=0;
	foreach $b (keys %types) {
		$found=1 if($a eq $b);
	}
        if(!$found) {
                %types = ( %types, $a => $count++ );
                @typeslist = ( @typeslist, $a );
        }
}

my %mods = ( "unknown" => 0 ) ;
my @modlist = ( "unknown" );
$count=1;
foreach $a (@fullmods) {
	$found=0;
	foreach $b (keys %mods) {
		$found=1 if($a eq $b);
	}
        if(!$found) {
                %mods = ( %mods, $a => $count++ );
                @modlist = ( @modlist, $a );
        }
}

# write 
for(my $a=0;$a<$i;$a++) {

	$cid[0]=substr($ids[$a],0,1);
	$cid[1]=substr($ids[$a],1,1);
	$cid[2]=substr($ids[$a],2,1);
	$cid[3]=substr($ids[$a],3,4);

	print F1 "{ { \'$cid[0]\',\'$cid[1]\',\'$cid[2]\' }, ".
		 "0x$cid[3], isapnp_mod_type[$types{$fulltypes[$a]}], ".
		 "isapnp_mod_module[$mods{$fullmods[$a]}] },\n";
}

foreach $a (@typeslist) {
	print F2 "\"$a\", \n";
}

foreach $a (@modlist) {
	print F3 "\"$a\", \n";
}


close(F1);
close(F2);
close(F3);
