#!/usr/bin/perl
# Carlos E. Gorges <carlos@techlinux.com.br>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
# Generate mca_mod_list.ids from the mcamod-list.lst file.

open S,	 "<mcamod-list.lst" || die();
open F1, ">../mca_mod_list.ids" || die();
while (<S>) {
	if(! ($_=~ /^[\ \n]$/ ) && ! ( $_ =~ /^#/ ) ) {
		my @l=split /\t/,$_; chomp($l[1]);
		die("Incomplete line: $_") if ( ! length($l[0]) || ! length($l[1]) );
		print F1 "{0x$l[0], \"$l[1]\"},\n";
	}
}
close(S);
close(F1);
