#!/usr/bin/perl
# Carlos E. Gorges <carlos@techlinux.com.br>
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
# Generate usb_mod_list.ids, usb_mod_type.ids and usb_mod_module.ids
# from the usbmod-list.lst file.

open S,	 "<usbmod-list.lst" || die();
while (<S>) {
	if(! ($_=~ /^[\ \n]$/ ) && ! ( $_ =~ /^#/ ) ) {
		my @l=split /\t/,$_; chomp($l[3]);
		die("Incomplete line: $_") if ( ! length($l[1]) || ! length($l[2]) || ! length($l[3]) );

		@ids=(@ids,$l[0]);
		@fulltypes=(@fulltypes,$l[1]);
		@fullmods=(@fullmods,$l[2]);
		@desc=(@desc,$l[3]);
		$i++;
	}
}
close(S);

open F1, ">../usb_mod_list.ids"	|| die();
open F2, ">../usb_mod_type.ids" || die();
open F3, ">../usb_mod_module.ids" || die();

my %types = ( "unknown" => 0 ) ;
my @typeslist = ( "unknown" );
$count=1;
foreach $a (@fulltypes) {
	$found=0;
	foreach $b (keys %types) {
		$found=1 if($a eq $b);
	}
        if(!$found) {
                %types = ( %types, $a => $count++ );
                @typeslist = ( @typeslist, $a );
        }
}

my %mods = ( "unknown" => 0 ) ;
my @modlist = ( "unknown" );
$count=1;
foreach $a (@fullmods) {
	$found=0;
	foreach $b (keys %mods) {
		$found=1 if($a eq $b);
	}
        if(!$found) {
                %mods = ( %mods, $a => $count++ );
                @modlist = ( @modlist, $a );
        }
}

# write 
for(my $a=0;$a<$i;$a++) {

	@b=split(/:/,$ids[$a]);

	print F1 "{ 0x$b[0], 0x$b[1], ".
		 "usb_mod_type[$types{$fulltypes[$a]}], ".
		 "usb_mod_module[$mods{$fullmods[$a]}], \"$desc[$a]\" },\n";
}

foreach $a (@typeslist) {
	print F2 "\"$a\", \n";
}

foreach $a (@modlist) {
	print F3 "\"$a\", \n";
}


close(F1);
close(F2);
close(F3);
