PKG_NAME="intel-vaapi-driver"
PKG_VERSION="1.8.3"
PKG_REV="1"
PKG_ARCH="x86_64"
PKG_LICENSE="GPL"
#PKG_GIT_URL="https://github.com/01org/intel-vaapi-driver"
PKG_URL="https://github.com/01org/intel-vaapi-driver/releases/download/$PKG_VERSION/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain libva libdrm"
PKG_PRIORITY="optional"
PKG_SECTION="multimedia"
PKG_SHORTDESC="intel-vaapi-driver: Intel G45+ driver for VAAPI"
PKG_LONGDESC="intel-vaapi-driver: Intel G45+ driver for VAAPI"

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"
