PKG_NAME="libressl"
PKG_VERSION="2.8.1"
PKG_SHA256="334bf7050f1db4087feebb30571ec13d9fa975bf05d6003ce3ab6d7d2452cf42"
PKG_ARCH="any"
PKG_LICENSE="BSD"
PKG_SITE="http://mirror.ox.ac.uk/pub/OpenBSD/LibreSSL/?C=M;O=D"
PKG_URL="http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain"
PKG_PRIORITY="optional"
PKG_SECTION="security"
PKG_SHORTDESC="libressl: a FREE version of the SSL/TLS protocol forked from OpenSSL"
PKG_LONGDESC="LibreSSL is a FREE version of the SSL/TLS protocol forked from OpenSSL"
PKG_TOOLCHAIN="autotools"
PKG_BUILD_FLAGS="+pic:host +pic"

PKG_CONFIGURE_OPTS_TARGET="--disable-shared"