PKG_NAME="lz4"
PKG_VERSION="1.8.0"
PKG_URL="https://fossies.org/linux/misc/$PKG_NAME-$PKG_VERSION.tar.xz"
PKG_DEPENDS_TARGET="toolchain"
PKG_DEPENDS_HOST="cmake:host"
PKG_SECTION="compress"
PKG_AUTORECONF="no"
PKG_USE_CMAKE="yes"
PKG_USE_NINJA="no"

PKG_CMAKE_SCRIPT="$PKG_BUILD/contrib/cmake_unofficial/CMakeLists.txt"

PKG_CMAKE_OPTS_HOST="-DCMAKE_INSTALL_PREFIX=$TOOLCHAIN -DBUILD_SHARED_LIBS=0 -DBUILD_STATIC_LIBS=1"

PKG_CMAKE_OPTS_TARGET="-DBUILD_SHARED_LIBS=0 -DBUILD_STATIC_LIBS=1"
