.TH BUILDER-C++ 1 "2002-03-02" "Debian Project" "Debian GNU/Linux"
.SH NAME
builder-c++ \- g++ wrapper to facilitate pentium-optimizations
.SH SYNOPSIS
.BI "export DEBIAN_BUILDARCH=" "architecture"
.br
.BI "export DEBIAN_BUILDGCCVER=" "gcc-version"
.br
.B g++
.I ...
.SH "DESCRIPTION"
The
.B builder-c++
wrapper is normally used by calling
.B g++
as usual. If the environment variable
.B DEBIAN_BUILDARCH
is not set,
.B builder-c++
does nothing, and the real
.B g++
is invoked with the specified arguments.

When the
.B DEBIAN_BUILDARCH
environment variable is set,
.B builder-c++
invokes
.B g++
with the specified arguments, plus
.IB "-mcpu=" "DEBIAN_BUILDARCH"
.IB "-march=" "DEBIAN_BUILDARCH"
This has the effect of telling
.B g++
to use architecture-specific optimizations without changing the
command line. This is particularly useful for package builds.

If
.B DEBIAN_BUILDGCCVER
is not set,
.B builder-c++ 
calls 
.BR g++.real .
If
.B DEBIAN_BUILDGCCVER
is set,
.B builder-c++
calls
.B g++-DEBIAN_BUILDGCCVER
instead.

.SH ENVIRONMENT
.IP DEBIAN_BUILDARCH
If set, the architecture to compile for. Useful values are
.B pentium
or
.BR pentiumpro .
.IP DEBIAN_BUILDGCCVER
If set, the version of g++ to be invoked.
Useful values are
.B 3.0
or 
.BR 2.95 .

.SH NOTES
The real
.B g++
is renamed
.BR g++.real , 
and a diversion is
registered with
.BR dpkg-divert (1).
Thus
.BR builder-c++ 's
idea of the default
.B g++
is dictated by whatever package installed
.IR /usr/bin/g++ .

.SH "SEE ALSO"
.BR g++ (1)
