PKG_NAME="pstate-frequency"
PKG_VERSION="ecbbfb1"
PKG_GIT_URL="https://github.com/pyamsoft/pstate-frequency"
PKG_DEPENDS_TARGET="toolchain udevil"
PKG_SECTION="tools"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
