PKG_NAME="attr"
PKG_VERSION="1.1.1"
PKG_REV="1"
PKG_URL="http://download.savannah.gnu.org/releases/attr/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain alsa-lib"
PKG_PRIORITY="optional"
PKG_SECTION="audio"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"

