PKG_NAME="libyaml"
PKG_VERSION="0.1.7"
PKG_SHA256="e1884d0fa1eec8cf869ac6bebbf25391e81956aa2970267f974a9fa5e0b968e2"
PKG_LICENSE="MIT"
PKG_SITE="http://pyyaml.org"
PKG_URL="https://github.com/yaml/$PKG_NAME/archive/$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain"
PKG_LONGDESC="yaml is the next generation YAML parser and emitter"
PKG_TOOLCHAIN="autotools"
PKG_BUILD_FLAGS="+pic"

PKG_CONFIGURE_OPTS_TARGET="--disable-shared --enable-static"
