PKG_NAME="numactl"
PKG_VERSION="2.0.11"
PKG_SITE="https://github.com/libevent/libevent/releases/"
#PKG_URL="https://github.com/libevent/libevent/releases/download/release-$PKG_VERSION/libevent-$PKG_VERSION.tar.gz"
PKG_URL="http://192.168.1.200:8080/%2Fnumactl-2.0.11.tar.gz"
PKG_DEPENDS_TARGET="toolchain"
PKG_SHORTDESC="libevent: a library for asynchronous event notification"
#PKG_TOOLCHAIN="autotools"
PKG_BUILD_FLAGS="+pic:host +pic"

PKG_CONFIGURE_OPTS_TARGET="--disable-shared --enable-static"
PKG_CONFIGURE_OPTS_HOST="$PKG_CONFIGURE_OPTS_TARGET"
