PKG_NAME="miniupnpc"
PKG_VERSION="2.0.20180410"
PKG_SITE="http://miniupnp.free.fr/files/"
PKG_URL="http://miniupnp.free.fr/files/miniupnpc-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain"
PKG_SECTION="system"
PKG_TOOLCHAIN="cmake-make"
PKG_BUILD_FLAGS="+pic"

PKG_CMAKE_OPTS_TARGET="-DUPNPC_BUILD_SHARED=0 -DUPNPC_BUILD_STATIC=1"