PKG_NAME="mkfontscale"
PKG_VERSION="1.2.1"
PKG_SITE="https://xorg.freedesktop.org"
PKG_URL="https://xorg.freedesktop.org/archive/individual/app/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_HOST="freetype:host libfontenc:host"
PKG_SHORTDESC="mkfontscale creates an index of scalable font files for X."
