PKG_NAME="libnfnetlink"
PKG_VERSION="20170818"
PKG_URL="ftp://ftp.netfilter.org/pub/libnfnetlink/snapshot/libnfnetlink-20170818.tar.bz2"
PKG_DEPENDS_TARGET="toolchain linux"
PKG_SECTION="my"
PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"