PKG_NAME="chromium-launcher"
PKG_VERSION="98890a9"
PKG_SITE="https://developers.google.com/protocol-buffers/"
PKG_GIT_URL="https://github.com/foutrelis/chromium-launcher"
PKG_SECTION="devel"
PKG_SHORTDESC="protobuf: Protocol Buffers - Google's data interchange format"
PKG_LONGDESC="protobuf: Protocol Buffers - Google's data interchange format"

PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
