PKG_NAME="ncdu"
PKG_VERSION="1.12"
PKG_URL="https://dev.yorhel.nl/download/ncdu-$PKG_VERSION.tar.gz"
#PKG_VERSION="e4f211d"
#PKG_GIT_URL="git://g.blicky.net/ncdu.git"
PKG_DEPENDS_TARGET="toolchain netbsd-curses"
PKG_SECTION="tools"
PKG_AUTORECONF="no"

PKG_CONFIGURE_OPTS_TARGET="--disable-nls --with-gnu-ld"