PKG_NAME="libtorrent-rasterbar"
PKG_VERSION="1.1.1"
PKG_URL="https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1_1/libtorrent-rasterbar-$PKG_VERSION.tar.gz"
#PKG_SOURCE_DIR="libtorrent_libtorrent-$PKG_VERSION"
PKG_DEPENDS_HOST="toolchain"
PKG_DEPENDS_TARGET="toolchain boost Python:host Python:target zlib bzip2 curl"
PKG_PRIORITY="optional"
PKG_SECTION="devel"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"

