PKG_NAME="acl"
PKG_VERSION="ff3bca"
PKG_URL="http://git.savannah.nongnu.org/cgit/acl.git/snapshot/acl-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain attr"
PKG_DEPENDS_HOST="toolchain attr:host"
PKG_SECTION="tools"
PKG_TOOLCHAIN="autotools"
PKG_BUILD_FLAGS="+pic"

PKG_CONFIGURE_OPTS_TARGET="--disable-shared --enable-static"