PKG_NAME="libnotify"
PKG_VERSION="0.7.7"
PKG_ARCH="any"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/GNOME/libnotify"
PKG_URL="https://github.com/GNOME/libnotify/archive/$PKG_VERSION.tar.gz"
#PKG_URL="https://s3.amazonaws.com/json-c_releases/releases/json-c-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain gdk-pixbuf"
PKG_SECTION="accessibility"
PKG_SHORTDESC="json-c"
PKG_LONGDESC="JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects"
PKG_TOOLCHAIN="autotools"

PKG_CONFIGURE_OPTS_TARGET="--enable-gtk-doc=no"
