PKG_NAME="nuttcp"
PKG_VERSION="8.1.3"
PKG_URL="http://nuttcp.net/nuttcp/beta/nuttcp-$PKG_VERSION.c"
PKG_DEPENDS_TARGET="toolchain"
PKG_PRIORITY="optional"
PKG_SECTION="my"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
