PKG_NAME="bc"
#PKG_VERSION="1.07.1"
PKG_VERSION="1.06.95"
PKG_URL="ftp://ftp.gnu.org/gnu/bc/bc-$PKG_VERSION.tar.gz"
PKG_URL="http://alpha.gnu.org/gnu/bc/bc-1.06.95.tar.bz2"
PKG_DEPENDS_HOST="bison:host flex:host"
PKG_TOOLCHAIN="autotools"
