PKG_NAME="bc"
PKG_VERSION="1.07.1"
PKG_URL="https://fossies.org/linux/misc/$PKG_NAME-$PKG_VERSION.tar.xz"
#PKG_URL="http://alpha.gnu.org/gnu/bc/bc-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_HOST="bison:host flex:host"
PKG_IS_ADDON="no"
PKG_AUTORECONF="no"