PKG_NAME="wireshark"
PKG_VERSION="2.2.12"
PKG_URL="https://www.wireshark.org/download/src/all-versions/wireshark-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain zlib libevent"
PKG_SECTION="security"
