#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

BACKUP_FILE=`ls -1 /storage/.restore/??????????????.tar 2>/dev/null | tail -1`

if [ -f "$BACKUP_FILE" ] ; then
  echo -en "please wait.. checking backup file: "
  tar tf $BACKUP_FILE &>/dev/null
  ret=$?
  if [ $ret -eq 0 ] ; then
    echo OK
    echo -en "restoring.. this may take long time to complete, please wait.. "
    rm -rf /storage/.kodi &>/dev/null
    rm -rf /storage/.cache &>/dev/null
    rm -rf /storage/.config &>/dev/null
    tar xf $BACKUP_FILE -C / &>/dev/null
    rm -f $BACKUP_FILE &>/dev/null
    echo done
    echo "rebooting in 5s..."
    sleep 5
  else
    echo FAILED
    rm -f $BACKUP_FILE &>/dev/null
    echo "rebooting in 30s..."
    sleep 30
  fi
fi
sync
reboot -f
