#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

get_target() {
  for arg in $(cat /proc/cmdline); do
    case $arg in
      disk=*)
        disk="${arg#*=}"
        case $disk in
          LABEL=*)
            label="${disk#*=}"
            target=`blkid -L $label`
            ;;
          UUID=*)
            uuid="${disk#*=}"
            target=`blkid -U $uuid`
            ;;
          /*)
            target=$disk
            ;;
        esac
        ;;
    esac
  done
}

if [ -f /storage/.cache/reset_oe ] ; then
  # hard reset
  rm -f /storage/.cache/reset_oe
  get_target
  if [ ! -z $target ] ; then
    echo "hard resetting..."
    umount /storage
    mke2fs -t ext4 -m 0 $target 2>&1 >/dev/null
    if [ ! -z $label ] ; then
      tune2fs -U random -L $label $target
    fi
    if [ ! -z $uuid ] ; then
      tune2fs -U $uuid $target
    fi
    echo "done"
    sleep 5
  fi
elif [ -f /storage/.cache/reset_xbmc ] ; then
  # soft reset
  rm -f /storage/.cache/reset_xbmc
  get_target
  if [ ! -z $target ] ; then
    echo "soft resetting..."
    rm -rf /storage/.??* 2>&1 >/dev/null
    echo "done"
    sleep 5
  fi
fi
sync
reboot -f
