PKG_NAME="sshfs"
PKG_VERSION="2.9"
PKG_SITE="https://github.com/libfuse/sshfs"
PKG_URL="https://github.com/libfuse/sshfs/releases/download/sshfs-$PKG_VERSION/sshfs-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain fuse netbsd-curses glib"
PKG_SECTION="tools"
PKG_AUTORECONF="yes"
