PKG_NAME="sshfs"
PKG_VERSION="40e2023"
PKG_SITE="https://github.com/libfuse/sshfs/tree/sshfs_2.x"
PKG_GIT_URL="https://github.com/libfuse/sshfs"
PKG_DEPENDS_TARGET="toolchain fuse ncurses glib"
PKG_SECTION="tools"
PKG_AUTORECONF="yes"