PKG_NAME="sshfs"
PKG_VERSION="2.10"
PKG_SITE="https://github.com/libfuse/sshfs/tree/sshfs_2.x"
PKG_URL="https://github.com/libfuse/sshfs/releases/download/sshfs-$PKG_VERSION/sshfs-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain fuse"
PKG_SECTION="tools"
PKG_TOOLCHAIN="configure"