PKG_NAME="bonnie"
PKG_VERSION="1.97.3"
PKG_URL="https://www.coker.com.au/bonnie++/experimental/bonnie++-1.97.3.tgz"
PKG_SOURCE_DIR="bonnie++-$PKG_VERSION"
PKG_DEPENDS_TARGET="toolchain"
PKG_SECTION="my"
PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"

#PKG_CONFIGURE_OPTS_TARGET="--enable-static"
