PKG_NAME="libssh2"
PKG_VERSION="f7daf31"
PKG_GIT_URL="https://github.com/libssh2/libssh2"
PKG_DEPENDS_TARGET="toolchain libz mbedtls"
PKG_IS_ADDON="no"
PKG_USE_CMAKE="yes"
PKG_AUTORECONF="no"

PKG_CMAKE_OPTS_TARGET="-DBUILD_EXAMPLES=OFF \
			  -DBUILD_SHARED_LIBS=OFF \
			  -DBUILD_TESTING=OFF \
			  -DCRYPTO_BACKEND="mbedTLS" \
			  -DENABLE_GEX_NEW=OFF \
			  -DENABLE_ZLIB_COMPRESSION=OFF \
			  -DENABLE_MAC_NONE=ON \
			  -DENABLE_CRYPT_NONE=ON"