PKG_NAME="zlib-ng"
PKG_VERSION="6a877a1"
PKG_URL="https://github.com/Dead2/zlib-ng/archive/${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET=""
PKG_DEPENDS_HOST=""
PKG_SECTION="compress"
PKG_AUTORECONF="no"
PKG_USE_CMAKE="yes"
PKG_USE_NINJA="no"

PKG_CMAKE_OPTS_TARGET="-DCMAKE_BUILD_TYPE=Release"
#PKG_CMAKE_OPTS_HOST="-DWITH_NATIVE_INSTRUCTIONS=ON -DZLIB_COMPAT=ON -DWITH_GZFILEOP=ON"

