#!/bin/sh -e

if [ "install" = "$1" ] || [ "upgrade" = "$1" ]; then
	dpkg-divert --package pentium-builder --add --rename \
		--divert /usr/bin/gcc.real /usr/bin/gcc
	dpkg-divert --package pentium-builder --add --rename \
		--divert /usr/bin/g++.real /usr/bin/g++
	# Clean up after an upgrade nightmare.
	if [ -f /usr/bin/c++ -a -e /usr/bin/c++.real ]; then
		rm -f /usr/bin/c++
	fi
fi

#DEBHELPER#
